### ISSUE TITLE
Allow override of path to third-party executables such as bun and pulumi

### ISSUE THREAD

**Issue by averagebit** [sst/ion#143]
The current implementation of `sst` is installing the `bun` executable in a predefined path and is ignoring executables available in the `$PATH`, which in turn makes `sst` commands that depend on `bun` fail on distributions such as NixOS due to it looking for dynamically linked libraries.

The implemented `NO_BUN` environment variable currently resolves that issue. A better long-term solution would be checking for existing binaries for things such as `bun` on the system before deciding whether to install them through the `sst` tool.

Relevant:
https://github.com/NixOS/nixpkgs/pull/300478

**Comment by thdxr** [comment]
the issue we have is what's available in the PATH might be the wrong version so we're choosing to statically link them. we depend on certain features in certain pulumi versions and imagine this may happen with bun as well - we used to use OS available versions and ran into some issues

that said i know this flies against how nix works since it has the capability to expose very specific versions to `sst` - i'm definitely willing to do something to support it better but would be nix specific as opposed to generally

**Comment by averagebit** [comment]
Would adding a new `ldflag` or prepending `nix-` to the `main.version` flag in the build time instructions for the Nix package be a viable solution to utilize for implementing a check that would scan the `$PATH` and error on missing third-party dependencies by default instead of installing them?

**Comment by thdxr** [comment]
that's a good idea if nix will be compiling its own binaries.  you can add a conditional here either at compile time or some runtime check [https://github.com/sst/ion/blob/dev/pkg/global/global.go#L121](https://github.com/sst/ion/blob/dev/pkg/global/global.go#L121) (there's one for pulumi path too) - just a call to \`exec.LookPath\` could work

**Comment by thdxr** [comment]
would accept a PR for this
