### ISSUE TITLE
Docs: List IAM permissions Ion needs

### ISSUE THREAD

**Issue by jayair** [sst/ion#165]
Similar to https://docs.sst.dev/advanced/iam-credentials#3-least-privilege-policies

https://discord.com/channels/983865673656705025/1177071497974648952/1224626254209220708

**Comment by cushdan** [comment]
I'm in the process of trying to determine the least privilege permissions for an ion nextjs deployment and this would be very helpful :)

**Comment by peguerosdc** [comment]
+1 also, it is confusing that [Ion's docs](https://ion.sst.dev/docs/start/aws/nextjs/) refer you to the old permissions. I spent hours trying to figure out why I was getting 403 errors in my first deploy (I have zero experience with aws, which is why I decided to take a look at SST) until I finally came across this issue to realize the policy is not updated and that I had to grant `AdministratorAccess`

**Comment by jayair** [comment]
Chat shared their progress with it: https://discord.com/channels/983865673656705025/1177071497974648952/1250954855787266110

**Comment by oczkowski** [comment]
I've been working out the policy for deploying an application with a domain attached. It's still a draft and I can't figure out fully the permissions for S3 but here's what I got so far.
[SST-policy.json](https://github.com/user-attachments/files/16164771/SST-policy.json)

The account in this draft is `123456789101` and all regions are allowed. Let me know if you have any tips. Thanks!

**Comment by jayair** [comment]
Added a list here https://sst.dev/docs/iam-credentials#iam-permissions
