### ISSUE TITLE
Is this an alternative to CDKTF ?

### ISSUE THREAD

**Issue by NoelJacob** [sst/ion#528]
I just want to suggest that a page showing differences between competitors might be helpful. For example, this can replace CDKTF by Terraform right?

**Comment by jayair** [comment]
Yeah we should add it to our docs.

**Comment by garysassano** [comment]
SST Ion is more an alternative to [Code Genie](https://codegenie.codes/), [Arc](https://arc.codes/) and [Wing](https://www.winglang.io/). Out of these, you could say that SST Ion and Wing are somewhat similar as one is a "Pulumi wrapper", while the other one is a "CDKTF wrapper". Of course, there are many other moving parts that they abstract and deploy for you besides the plain cloud infrastructure.

**Comment by garysassano** [comment]
SST Ion is more an alternative to [Code Genie](https://codegenie.codes/), [Arc](https://arc.codes/) and [Wing](https://www.winglang.io/). Out of these, you could say that SST Ion and Wing are somewhat similar as one is a "Pulumi wrapper", while the other one is a "CDKTF/CDK wrapper". Of course, there are many other moving parts that they abstract and deploy for you besides the plain cloud infrastructure.

**Comment by garysassano** [comment]
SST Ion is more an alternative to [Code Genie](https://codegenie.codes/), [Architect](https://arc.codes/) and [Wing](https://www.winglang.io/). Out of these, you could say that SST Ion and Wing are somewhat similar as one is a "Pulumi wrapper", while the other one is a "CDKTF/CDK wrapper". Of course, there are many other moving parts that they abstract and deploy for you besides the plain cloud infrastructure.

**Comment by joekiller** [comment]
Gary's answer may be sufficient to close this issue but since it's still open I'll toss a bit more than a, I'd like a comparison too please!

It would be helpful to understand the rationale of deciding to utilize a "Pulumi wrapper" instead of a "CDK" wrapper. It could simply be, we were using Pulumi and like it. Or, CDKTF was too immature, CDKTF lacks Level 2 constructs, etc.

The https://sst.dev/blog/moving-away-from-cdk.html article lays out a few arguments such as "fully open source" and zero purchase which is true with some caveats that are apt for Terraform and Pulumi in that each sell state management dashboards for profit.

An updated perspective would be helpful to other practitioners making similar decisions. Thanks for sharing your insights.

**Comment by jayair** [comment]
Yeah I'm going to add this to an FAQ.

**Comment by jayair** [comment]
There are a couple of big things:

1. [Higher level components](https://ion.sst.dev/docs/components/) (like Nextjs or Realtime) that are meant for full-stack developers.
2. SDKs that [link the infrastructure to the runtime or application code](https://ion.sst.dev/docs/linking/)
3. And the focus on the local developer experience with [Live](https://ion.sst.dev/docs/live/) and [`sst dev`](https://ion.sst.dev/docs/reference/cli/#dev)

**Comment by jayair** [comment]
Added this to FAQ https://sst.dev/docs/#faq

Let me know if it needs more info.
