### ISSUE TITLE
Blessed path for Multiple Account Setup?

### ISSUE THREAD

**Issue by AWebOfBrown** [sst/ion#768]
What's the suggested method for creating multiple account architectures? 

To give a specific example, I'm setting up an AWS org with a fairly simple account structure:
- Root management account (near nothing deployed in it)
- Development
- Production
- Security (delegated as admin for e.g. cloudtrail org trail, security hub, config etc).

The docs are a little light on how this could be structured. There's some mention of using providers here https://github.com/sst/ion/issues/152 but I'm not sure how this would look. 

Say I'm assuming a role with OIDC in github actions, how would I deploy a config file with constructs tied to multiple providers? Or is this somewhat outside the scope of SST at the moment? My immediate need is to delegate administration in the root account and create an org trail in the security account. 

Edit: My current workaround has been to use branched workflows for different accounts, but the goal was to keep it all on main for simplicity

**Comment by thdxr** [comment]
so i typically do everything pivoting off the stage<br><br>i will deploy `dev` to the dev aws account<br>\`production\` to the production aws account<br><br>the sst.config.ts itself is unaware of this except that some resources might be different based on which stage it's in - eg dev database might be configured with a smaller size<br><br>this works if your application does not need to deploy resources across multiple accounts for a single stage - this is *usually* the case and it sounds like your setup<br><br>for github oidc i just deploy it through sst just for the production and dev stages - although i'm not entirely sure of your question<br><br>long story short - i don't *think* you need to be messing around with having multiple aws providers from what you're describing?

**Comment by abrown-financeable** [comment]
> so i typically do everything pivoting off the stagei will deploy `dev` to the dev aws account`production` to the production aws accountthe sst.config.ts itself is unaware of this except that some resources might be different based on which stage it's in - eg dev database might be configured with a smaller sizethis works if your application does not need to deploy resources across multiple accounts for a single stage - this is _usually_ the case and it sounds like your setupfor github oidc i just deploy it through sst just for the production and dev stages - although i'm not entirely sure of your questionlong story short - i don't _think_ you need to be messing around with having multiple aws providers from what you're describing?

I think this is relatively straightforward for my dev and production accounts, because for our workload accounts, 'stages' exist. 

This isn't the case for e.g. my security account and root account provisioning SSO access to all other accounts (might not be ideally placed in the root account, but if I had a dedicated SSO account the point would remain). These accounts are 'aggregating' accounts, ie aggregating Security Hub findings across the entire org and all OUs, and likewise with IAM (managing the roles available for each employee across the entire org). 

By analogy, I'm wondering if SST can be used to replace org-formation or landing zones. Do you do something different here for SST's AWS org?

**Comment by AWebOfBrown** [comment]
Posted on my work account above, but going to assume this isn't catered to atm, will close
