### ISSUE TITLE
Inconsistent behavior with aws credentials

### ISSUE THREAD

**Issue by chrisandrewcl** [sst/ion#781]
I've encountered an issue with aws provider credentials: I have hardcoded a profile "A" in the config but also have the `AWS_PROFILE` env var set to "B". Ion starts using the profile A but then fails during deploy because it tries to use profile B (which doesn't exist in my case).

**Comment by coronapl** [comment]
Are you having the following problem as well?
```
default_6_47_0 pulumi:providers:aws
   pulumi:providers:aws resource 'default_6_47_0' has a problem: unable to validate AWS credentials.
Details: retrieving credentials: static credentials are empty   
```

**Comment by thdxr** [comment]
this was due to some different behavior in previous versions of sst and resources that were created with it. this issue is fixed for new resources going forward<br><br>a way to fix this is to do `sst state edit` - look for all fiends with `profile: "OLD-PROFILE` and remove them<br><br>it's possible an `sst refresh` could fix this too but not sure
