### ISSUE TITLE
listen tcp: lookup localhost on 8.8.8.8:53: no such host after upgrading to ion 0.1.76

### ISSUE THREAD

**Issue by abnud11** [sst/ion#801]
I was using ion 0.1.55 before upgrading to 0.1.76.

For some reason, I now get this error when using `--verbose` flag:

> level=ERROR msg="exited with error" err="listen tcp: lookup localhost on 8.8.8.8:53: no such host"

I don't have anything changed in `/etc/hosts`(it's actually empty), also `ping localhost` works correctly with ip set to `127.0.0.1` not `8.8.8.8`, I don't even know why is it expected for localhost to be on `8.8.8.8:53`.

I'm not sure if this is relevant but my docker work correctly, it runs `hello-world` without issues.

My OS is Arch Linux x64.
The command that's failing is `sst deploy --verbose --stage=development`.

**Comment by jayair** [comment]
Does this not happen with 0.1.55?

**Comment by abnud11** [comment]
No it doesn't happen

**Comment by abnud11** [comment]
> Does this not happen with 0.1.55?

@jayair No it doesn't happen

**Comment by abnud11** [comment]
Ok, turns out it's something in my networks config, for some reason my dns server didn't resolve `localhost` and didn't respect `/etc/hosts`, I solved the problem by installing `dnsmasq`, configuring NetworkManager to use it then used this answer to solve the problem:
https://askubuntu.com/a/737123/397359

Thank you for your good work

**Comment by BOTKooper** [comment]
Hi folks, sorry for necroposting a bit, but i encountered same issue (already resolved myself, but might be useful for others)

OS: Arch x64, gnome 46/47
sst: latest

Mentioned it in Dax's stream chat, he thought out loud that you should do `127.0.0.1` instead of `localhost` and call it a day

Why it happened to me:
I manually specified cloudflare as my dns for wifi, and **_ticked-off_** `Automatic DNS` selector in network settings

Under those conditions ion tried to find `localhost` in my tailscale dns (100.x.x.x:53), after shutting tailscale down - ion moved lookup to `1.1.1.1:53` 

Changing that stupid selector **_back to_** default `Automatic` resovled the issue for me


Image (cursor is at the selector i'm talking about):
![image](https://github.com/user-attachments/assets/3c43a4f5-77f4-46ed-b281-1e6dc9fe7202)


Why this can't be used as a solution (only as a workaround) - it _seems like_ not disabling that selector tells OS to ignore user-provided option (and possibly get stuck with ISP dns servers)

![image](https://github.com/user-attachments/assets/2b8a7af8-3a2d-4d15-a4bd-53b3a31a5d63)
