### ISSUE TITLE
The symbol "aws" has already been declared

### ISSUE THREAD

**Issue by ryanleecode** [sst/ion#830]
If a file in a `dist` folder in a subpackage contains an `aws` import sst will fail with `The symbol "aws" has already been declared`.

**Comment by thdxr** [comment]
hey we need a bit more info - what dist folder? and what subpackage?

**Comment by ryanleecode** [comment]
> hey we need a bit more info - what dist folder? and what subpackage?

Repo here: https://github.com/ryanleecode/sst-830

**Comment by thdxr** [comment]
in your setup you are importing things from `@aws/pulumi` - this isn't something we support and we should error more explicitly.<br><br>also you should not have import statements in your sst.config.ts - you can dynamically import stuff in the `run()` function - we need to catch and error on this<br><br>overall this is quite a complicated setup with trying to use a subpackage - is there a reason you're going down this route? we're unlikely not setup yet to support this

**Comment by ryanleecode** [comment]
i had to fork remotion sst so i thought it would be good as sub pkg

https://github.com/karelnagel/remotion-sst

**Comment by thdxr** [comment]
yeah so our bundler injects `import * as aws from "@pulumi/aws"` into every file which is why you're experiencing this.  can you import as a different name as a workaround?<br><br>we have ideas on other ways to implement the globals but the one we have right now has a lot of benefits so i need to think about this more<br><br>closing for now but continuing to consider it
